/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        accent: 'var(--color-accent)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        text: 'var(--color-text)',
        'text-secondary': 'var(--color-textSecondary)',
        border: 'var(--color-border)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        // Cyber colors
        'cyber-blue': 'var(--color-cyber-blue)',
        'cyber-green': 'var(--color-cyber-green)',
        'cyber-purple': 'var(--color-cyber-purple)',
        'cyber-pink': 'var(--color-cyber-pink)',
        'cyber-orange': 'var(--color-cyber-orange)',
        'neon-red': 'var(--color-neon-red)',
        'dark-bg': 'var(--color-dark-bg)',
        'dark-surface': 'var(--color-dark-surface)',
        'dark-accent': 'var(--color-dark-accent)',
        // Gray scale for compatibility
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
          950: '#030712',
        },
      },
      fontFamily: {
        cyber: ['Orbitron', 'monospace'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Orbitron', 'monospace'],
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up': 'slide-up 0.3s ease-out',
        'slide-down': 'slide-down 0.3s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'neon-pulse': 'neon-pulse 2s ease-in-out infinite alternate',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'spin': 'spin 1s linear infinite',
      },
      boxShadow: {
        'neon': '0 0 20px color-mix(in srgb, var(--color-cyber-blue) 50%, transparent)',
        'neon-green': '0 0 20px color-mix(in srgb, var(--color-cyber-green) 50%, transparent)',
        'neon-purple': '0 0 20px color-mix(in srgb, var(--color-cyber-purple) 50%, transparent)',
        'cyber': '0 4px 20px color-mix(in srgb, var(--color-cyber-blue) 30%, transparent)',
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
        '3xl': '4rem',
      },
    },
  },
  plugins: [],
} 